"""Shared fixtures for ingrid-py tests."""

from pathlib import Path

import pytest

from ingrid_py import GridConfig, WordList

# Path to the bundled Spread The Word List dictionary shipped with ingrid_core.
# Format: `word;score` per line (315K entries).
STWL_PATH = (
    Path(__file__).parents[2] / "ingrid_core" / "resources" / "spreadthewordlist.dict"
)

# A comprehensive set of common 3-letter English words at high score so that
# the fill engine has enough options to find a valid 3×3 fill quickly.
WORDS_3: list[tuple[str, int]] = [
    (w, 70)
    for w in [
        "ace",
        "act",
        "add",
        "age",
        "ago",
        "aid",
        "aim",
        "air",
        "ale",
        "all",
        "alm",
        "and",
        "ant",
        "ape",
        "arc",
        "are",
        "ark",
        "arm",
        "art",
        "ash",
        "ask",
        "ate",
        "awe",
        "axe",
        "aye",
        "bag",
        "ban",
        "bar",
        "bat",
        "bay",
        "bed",
        "bet",
        "bid",
        "big",
        "bit",
        "bog",
        "bow",
        "box",
        "bud",
        "bug",
        "bun",
        "bus",
        "but",
        "buy",
        "cab",
        "can",
        "cap",
        "car",
        "cat",
        "cob",
        "cod",
        "cog",
        "cop",
        "cot",
        "cow",
        "cry",
        "cub",
        "cup",
        "cut",
        "dab",
        "dam",
        "dew",
        "dig",
        "dim",
        "dip",
        "doe",
        "dog",
        "dot",
        "dug",
        "dun",
        "ear",
        "eat",
        "egg",
        "ego",
        "elf",
        "elm",
        "end",
        "era",
        "eve",
        "ewe",
        "eye",
        "fad",
        "fan",
        "far",
        "fat",
        "fax",
        "fed",
        "fen",
        "few",
        "fib",
        "fig",
        "fin",
        "fit",
        "fix",
        "fly",
        "fog",
        "for",
        "fox",
        "fry",
        "fun",
        "fur",
        "gag",
        "gap",
        "gas",
        "gel",
        "gem",
        "get",
        "gig",
        "gin",
        "gnu",
        "god",
        "got",
        "gun",
        "gut",
        "had",
        "hag",
        "ham",
        "has",
        "hat",
        "hay",
        "hen",
        "hew",
        "hid",
        "him",
        "hip",
        "his",
        "hit",
        "hob",
        "hog",
        "hop",
        "hot",
        "how",
        "hub",
        "hue",
        "hug",
        "hut",
        "ice",
        "icy",
        "ill",
        "imp",
        "inn",
        "ion",
        "ire",
        "ivy",
        "jab",
        "jag",
        "jam",
        "jar",
        "jaw",
        "jet",
        "job",
        "jot",
        "joy",
        "jug",
        "jut",
        "keg",
        "ken",
        "key",
        "kid",
        "kin",
        "kit",
        "lag",
        "lap",
        "lard",
        "law",
        "lax",
        "lay",
        "lea",
        "led",
        "leg",
        "let",
        "lid",
        "lip",
        "lit",
        "log",
        "lot",
        "lug",
        "mad",
        "man",
        "map",
        "mar",
        "mat",
        "maw",
        "men",
        "met",
        "mid",
        "mob",
        "mod",
        "mop",
        "mud",
        "mug",
        "nab",
        "nag",
        "nap",
        "nod",
        "nor",
        "not",
        "now",
        "nun",
        "nut",
        "oak",
        "oar",
        "oat",
        "odd",
        "ode",
        "off",
        "old",
        "one",
        "orb",
        "ore",
        "our",
        "out",
        "owe",
        "own",
        "pad",
        "pan",
        "par",
        "pat",
        "paw",
        "pay",
        "pea",
        "peg",
        "pen",
        "pew",
        "pie",
        "pig",
        "pin",
        "pit",
        "pod",
        "pot",
        "pun",
        "pup",
        "put",
        "ram",
        "ran",
        "rap",
        "rat",
        "raw",
        "ray",
        "red",
        "ref",
        "rep",
        "ret",
        "rib",
        "rid",
        "rig",
        "rim",
        "rip",
        "rob",
        "rod",
        "rot",
        "row",
        "rub",
        "rug",
        "rum",
        "run",
        "rut",
        "sac",
        "sad",
        "sag",
        "sap",
        "sat",
        "saw",
        "say",
        "set",
        "sew",
        "shy",
        "sin",
        "sip",
        "sir",
        "sit",
        "ski",
        "sky",
        "sly",
        "sob",
        "sod",
        "son",
        "sop",
        "sow",
        "spa",
        "spy",
        "sub",
        "sue",
        "sum",
        "sun",
        "tab",
        "tan",
        "tap",
        "tar",
        "tax",
        "tea",
        "ten",
        "the",
        "tie",
        "tin",
        "tip",
        "toe",
        "ton",
        "too",
        "top",
        "tug",
        "tun",
        "two",
        "urn",
        "use",
        "van",
        "vat",
        "via",
        "vow",
        "war",
        "was",
        "wax",
        "way",
        "web",
        "wed",
        "wet",
        "who",
        "wig",
        "win",
        "wit",
        "woe",
        "wok",
        "won",
        "woo",
        "yak",
        "yam",
        "yap",
        "yew",
        "you",
        "yet",
    ]
]

# A small 3×3 fully-open grid (no blocks).
GRID_3X3 = "...\n...\n..."


@pytest.fixture
def words_3() -> list[tuple[str, int]]:
    return WORDS_3


@pytest.fixture
def word_list(words_3) -> WordList:
    return WordList(words_3)


@pytest.fixture
def grid_3x3(word_list) -> GridConfig:
    return GridConfig(GRID_3X3, word_list, min_score=50)


@pytest.fixture(scope="session")
def stwl_word_list() -> WordList:
    """Load the bundled Spread The Word List dictionary (315K words, session-scoped)."""
    text = STWL_PATH.read_text(encoding="utf-8")
    # STWL uses `word;score` — convert to the tab-separated format from_text expects.
    tsv = "\n".join(
        line.replace(";", "\t", 1) for line in text.splitlines() if ";" in line
    )
    return WordList.from_text(tsv)
